### ISSUE TITLE
Slides require password

### ISSUE THREAD

**Issue by francishero** [sdras/intro-to-vue#1] opened 2017-07-15 02:36 UTC
Please provide the password to view slides

**Comment by denbatte** [comment] 2017-07-15 06:49
Please scan trough the readme and the password will be there.

!vue!

**Comment by elhanarinc** [comment] 2017-07-15 11:32
it says wrong password for *!vue!*

**Comment by sdras** [comment] 2017-07-15 12:31
I just went through and checked all of them in another browser, they seem to be working fine, can you please give me a little more detail about what's not working for you? Which deck, and are you sure you're typing !vue!  ? Thanks

**Comment by elhanarinc** [comment] 2017-07-15 17:49
I have checked every link with chrome browser and noone seems to be working with !vue! password.

**Comment by sdras** [comment] 2017-07-15 17:53
Hm, that's so strange, let me see if I can borrow another machine and test because I can't duplicate in any browser. Stay tuned. What OS are you on?

**Comment by melniker** [comment] 2017-07-16 01:57
I can confirm that the passwd worked for me for deck 1. 

Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/59.0.3071.102 Mobile/14F89 Safari/602.1

**Comment by elhanarinc** [comment] 2017-07-16 21:56
I am using win 10 education with chrome 59.0.3071.115 version 64bit. 
Thanks !

**Comment by sdras** [comment] 2017-07-16 22:42
wat.

OK I just tried on chrome (same version) with win 10 home and it's loading ok- sorry to make you do this but could you try deleting cookies and hard refreshing and try again?

**Comment by elhanarinc** [comment] 2017-07-17 12:05
I found the problem. I am using *HTTPS Everywhere* extension with my chrome so it checks the website served with HTTPS and if it not extension does not load the website.
Disabling it gave me the slides. 
![](https://media.giphy.com/media/3osxYlhbYjOIDEZhkI/giphy.gif)

**Comment by sdras** [comment] 2017-07-17 14:35
Awesome, I was hoping it was something like that. Closing this out. 🤘🏼

**Closed by sdras** 2017-07-17 14:35 UTC

**Comment by TheInternerd12** [comment] 2017-07-21 20:38
@sdras could you add this as a side note to the README? Would be awesome, thx 👍
